version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ Service
      - "15672:15672"  # RabbitMQ Management Plugin (interface web)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"  # Porta para o Redis
    volumes:
      - redis_data:/data
    networks:
      - my_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"  # Elasticsearch
      - "9300:9300"  # Elasticsearch (comunicação entre nós)
    networks:
      - my_network

  web:
    build:
      context: ./Konsi.Web
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - my_network

  crawler:
    build:
      context: ./Konsi.Crawler
    container_name: crawler
    depends_on:
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - my_network

  api:
    build:
      context: ./Konsi.API
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
